# Generated by Django 4.1 on 2022-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_pictures_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pictures",
            name="picture",
            field=models.ImageField(upload_to="articlesPictures"),
        ),
    ]
