# Generated by Django 4.1 on 2022-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_pictures_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="filePrincipal",
            field=models.FileField(default=None, upload_to="webPage/"),
        ),
    ]
