# Generated by Django 4.1 on 2022-08-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
            ("store", "0011_articles_serie"),
    ]

    operations = [
        migrations.RemoveField(model_name="articles", name="serie",),
    ]
