# Generated by Django 4.1 on 2022-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_articles_serie"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="availablity",
            field=models.BooleanField(default=True),
        ),
    ]
