# Generated by Django 4.1 on 2022-08-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_series_availablity"),
    ]

    operations = [
        migrations.RemoveField(model_name="articles", name="serie",),
        migrations.DeleteModel(name="Series",),
    ]
