# Generated by Django 4.1 on 2022-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_articles_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="filePrincipal",
            field=models.FileField(default=None, upload_to="Article/"),
        ),
    ]
