# Generated by Django 4.1 on 2022-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_alter_articles_fileprincipal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="filePrincipal",
            field=models.TextField(default="", max_length=70000),
        ),
    ]
