# Generated by Django 4.1 on 2022-08-23 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_alter_articles_fileprincipal"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="users",
            field=models.ManyToManyField(
                related_name="articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
