# Generated by Django 4.1 on 2022-08-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_articles_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="articles",
            field=models.ForeignKey(
                #default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="store.articles",
            ),
        ),
        migrations.AddField(
            model_name="comments", name="note", field=models.IntegerField(default=0),
        ),
    ]
