# Generated by Django 4.1 on 2022-08-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_comments_articles_comments_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="articles",
            field=models.ForeignKey(
                #default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="store.articles",
            ),
        ),
    ]
