# Generated by Django 4.1 on 2022-08-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_alter_comments_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="likeBad",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comments",
            name="likeGood",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comments",
            name="numberVisited",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comments",
            name="articles",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="store.articles",
            ),
        ),
    ]
