# Generated by Django 4.1 on 2022-09-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_comments_likebad_comments_likegood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likeBad',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likeGood',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='note',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='numberVisited',
        ),
        migrations.AddField(
            model_name='comments',
            name='isNoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='typeNote',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeGood', models.BigIntegerField(default=0)),
                ('likeBad', models.BigIntegerField(default=0)),
                ('numberVisited', models.BigIntegerField(default=0)),
                ('articles', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='store.articles')),
            ],
        ),
    ]
